### ISSUE TITLE
installation problem on Ubuntu Linux

### ISSUE THREAD

**Issue by Guang91** [onsala-space-observatory/UVMultiFit#4]
Hi, 

I tried to install UVMultiFit on my Ubuntu Linux. But got the error below:
**can't find 'Python.h' in your casa installation**

Could you help me fix that? 
My casa is the most recent version (v6.4.0). 

Thanks,
Guang

**Comment by molberg** [comment]
Hi Guang,

This most likely means that you need to install 'libpython3-dev':

$ sudo apt update 
$ sudo apt install libpython3-dev

That should fix the error message you are getting.

Please note that we haven't tested UVMultiFit on casa v 6.4 yet. You are welcome to report
back how it works out for you.

kind regards,
Michael

**Comment by Guang91** [comment]
Thanks for the reply. 
I have installed libpython3-dev, but still have the same error after "make install". 
I checked my casa directly. There is no file called "Python.h". Is this a CASA version issue?

**Comment by Guang91** [comment]
okay, I just realized the Python.h is in another directory in CASA6.4. 
So, I have to modify the following lines in setup.py
CASA_PYTHON_INCLUDE = CASA_INSTALLATION + "/include/python2.7"
CASA_PYTHON_SITE_PACKAGES = CASA_INSTALLATION + "/lib/python2.7/site-packages"
-->
CASA_PYTHON_INCLUDE = CASA_INSTALLATION + "/lib/py/include/python3.8"
CASA_PYTHON_SITE_PACKAGES = CASA_INSTALLATION + "/lib/py/lib/python3.8/site-packages"

But now, I have new issues: 
_uvmultimodel.cpp:177:19: error: 'Py_InitModule3' was not declared in this scope
  177 |     PyObject *m = Py_InitModule3("_uvmultimodel", module_methods, module_docstring);
I realized it was a compiler issue after some googling (https://stackoverflow.com/questions/50323877/python3-mlpy-installation-error-py-initmodule3-was-not-declared-in-this-scop)

So, I use old versions of gcc & g++. But this leads to another issue:
gcc-5: error: unrecognized command line option ‘-fno-plt’
Again, google says I should use a new gcc & g++ (https://stackoverflow.com/questions/46504700/gcc-compiler-not-recognizing-fno-plt-option)

I can't find a version that deals with both issues. 
Which gcc version are you using to compile? 

-Guang

**Comment by molberg** [comment]
Hi Guang,

I'll try to build it myself for casa 6.4 during the next couple of days.

In the meantime, assuming you got the code via our repository on github, are you sure you
downloaded the casa 6 branch of UVMultiFit? That one should not have had a reference to
python2.7.

cheers,
Michael

**Comment by Guang91** [comment]
Oops, I didn't realize there's a casa6 branch. 
Using the casa6 branch, I got many "does not name a type" errors, like

/home/guang/anaconda3/x86_64-conda-linux-gnu/sysroot/usr/include/stdlib.h:96:1: error: '__BEGIN_NAMESPACE_STD' does not name a type
   96 | __BEGIN_NAMESPACE_STD

Best,
Guang

**Comment by Guang91** [comment]
@molberg  just a reminder :smiley:
